modLoader="javafml"
loaderVersion="[41,)"
license="GNU GPL 3.0"
issueTrackerURL="https://github.com/RecraftorsMC/Chests-are-Chests/issues"
[[mods]]
   modId="chests_are_chests"
   version="${version}"
   displayName="chests are chests"
   displayURL="https://github.com/RecraftorsMC/Chests-are-Chests"
   logoFile="icon.png"
   authors="Recraftors Team, Nerjal Nosk"
   displayTest="IGNORE_SERVER_VERSION"
   description="Allows items to fall into open containers"
[[dependencies.chests_are_chests]]
   modId="forge"
   mandatory=true
   versionRange="[41,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.chests_are_chests]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.chests_are_chests]]
   modId="unruled_api"
   mandatory=true
   versionRange="*"
   ordering="NONE"
   side="BOTH"
